"""
Core Coder V5 - CLI Interface
================================================

Self-contained CLI that loads configuration from agent_config.json.
All agent setup, tools, and features are handled here.

Generated by Agent Forge™
"""

import sys
import os
import json
from pathlib import Path
from typing import List, Optional

try:
    from colorama import init, Fore, Style, Back, just_fix_windows_console
    just_fix_windows_console()
except (ImportError, AttributeError):
    from colorama import init, Fore, Style, Back
    init()

from dotenv import load_dotenv
load_dotenv()

# Add langchain-agent-base to path
sys.path.insert(0, str(Path(__file__).parent / "langchain-agent-base" / "src"))
sys.path.insert(0, str(Path(__file__).parent))

from langchain_core.tools import tool
from base import Agent
from toolbox import get_toolbox

# For shell middleware
try:
    from langchain.agents.middleware import ShellToolMiddleware, HostExecutionPolicy
    SHELL_MIDDLEWARE_AVAILABLE = True
except ImportError:
    SHELL_MIDDLEWARE_AVAILABLE = False


# ============================================================================
# LOAD CONFIGURATION FROM agent_config.json
# ============================================================================

CONFIG_FILE = Path(__file__).parent / "agent_config.json"

def load_config() -> dict:
    """Load agent configuration from JSON file."""
    if CONFIG_FILE.exists():
        with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
            return json.load(f)
    else:
        raise FileNotFoundError(f"Configuration file not found: {CONFIG_FILE}")

def save_config(updates: dict = None):
    """Save configuration updates back to JSON file."""
    global AGENT_CONFIG
    if updates:
        AGENT_CONFIG.update(updates)
    with open(CONFIG_FILE, 'w', encoding='utf-8') as f:
        json.dump(AGENT_CONFIG, f, indent=2)

# Load config on startup
AGENT_CONFIG = load_config()


# ============================================================================
# SIMPLE CONVERSATION MEMORY
# ============================================================================

class SimpleConversationMemory:
    """Simple in-memory conversation history."""
    
    def __init__(self, max_messages: int = 20):
        self.max_messages = max_messages
        self.history = {}
    
    def add_message(self, session_id: str, message: str, response: str):
        if session_id not in self.history:
            self.history[session_id] = []
        self.history[session_id].append({"message": message, "response": response})
        if len(self.history[session_id]) > self.max_messages:
            self.history[session_id] = self.history[session_id][-self.max_messages:]
    
    def get_history(self, session_id: str, limit: int = None) -> list:
        history = self.history.get(session_id, [])
        return history[-limit:] if limit else history
    
    def clear(self, session_id: str = None):
        if session_id:
            self.history.pop(session_id, None)
        else:
            self.history.clear()
    
    def get_message_count(self, session_id: str) -> int:
        return len(self.history.get(session_id, []))

_simple_memory = SimpleConversationMemory()


# ============================================================================
# BANNER DISPLAY
# ============================================================================

def print_banner():
    """Display ASCII art banner and/or pixel art from config."""
    ascii_config = AGENT_CONFIG.get('ascii_art', {})
    banner_order = ascii_config.get('banner_order', 'banner-first')
    show_banner = ascii_config.get('show_font_banner') and ascii_config.get('font_banner')
    show_pixel = ascii_config.get('show_pixel_art') and ascii_config.get('pixel_art')
    
    def display_ascii_banner():
        if show_banner:
            color = ascii_config.get('font_banner_color', '#00FF00')
            banner_text = ascii_config.get('font_banner', '')
            if color.startswith('#') and len(color) == 7:
                r = int(color[1:3], 16)
                g = int(color[3:5], 16)
                b = int(color[5:7], 16)
                print("\033[38;2;" + str(r) + ";" + str(g) + ";" + str(b) + "m" + banner_text + "\033[0m")
            else:
                print(banner_text)
            print()
    
    def display_pixel_art():
        if show_pixel:
            pixel_art = ascii_config.get('pixel_art', '')
            # Pixel art already contains actual ANSI escape characters from export
            print(pixel_art)
            print()
    
    if banner_order == 'pixel-first':
        display_pixel_art()
        display_ascii_banner()
    else:
        display_ascii_banner()
        display_pixel_art()


# ============================================================================
# AGENT FACTORY
# ============================================================================

def create_agent(project_root: str = ".", **kwargs):
    """Create agent instance from configuration."""
    
    # Load tools from configured toolboxes
    tools = []
    seen_tools = set()
    
    toolbox = get_toolbox()
    for toolbox_name in AGENT_CONFIG.get('toolboxes', ['coding']):
        try:
            category_tools = toolbox.get_tools_by_category(toolbox_name)
            for t in category_tools:
                tool_name = getattr(t, 'name', str(t))
                if tool_name not in seen_tools:
                    tools.append(t)
                    seen_tools.add(tool_name)
            print(f"✓ Loaded tools from '{toolbox_name}' toolbox")
        except Exception as e:
            print(f"⚠ Could not load toolbox '{toolbox_name}': {e}")
    
    print(f"✓ Total unique tools loaded: {len(tools)}")
    
    # Get config values
    enable_memory = kwargs.pop('enable_memory', AGENT_CONFIG.get('enable_memory', False))
    model_name = AGENT_CONFIG.get('model_name', 'openai/gpt-oss-120b')
    provider = AGENT_CONFIG.get('provider', 'groq')
    temperature = AGENT_CONFIG.get('temperature', 0.7)
    system_prompt = AGENT_CONFIG.get('system_prompt', 'You are a helpful assistant.')
    
    # Build agent parameters
    agent_params = {
        'name': AGENT_CONFIG.get('name', 'agent'),
        'system_prompt': system_prompt,
        'tools': tools,
        'model_name': model_name,
        'provider': provider,
        'temperature': temperature,
        'enable_memory': enable_memory,
    }
    
    # Add shell middleware if enabled
    if AGENT_CONFIG.get('enable_shell', True) and SHELL_MIDDLEWARE_AVAILABLE:
        agent_params['enable_shell_tool'] = True
        agent_params['workspace_root'] = project_root or '.'
        agent_params['shell_timeout'] = 120
        print(f"✓ Shell enabled with workspace: {agent_params['workspace_root']}")
    
    agent_params.update(kwargs)
    return Agent(**agent_params)


# Alias for class-style usage
CoreCoderV5 = create_agent


class Colors:
    """Handle color schemes for the CLI."""
    
    SCHEMES = {
        "custom": {
            "agent": "\033[38;2;240;188;241m",
            "user": "\033[38;2;247;54;221m",
            "system": "\033[38;2;117;243;32m",
            "command": "\033[38;2;52;249;173m",
            "tool": "\033[38;2;10;137;235m",
            "shell": "\033[38;2;123;80;242m",
            "output": "\033[38;2;0;250;233m",
            "error": "\033[38;2;243;43;53m",
            "success": "\033[38;2;0;250;233m",
            "warning": "\033[38;2;241;219;75m",
            "dim": "\033[2m",
            "reset": "\033[0m"
        },
        "dracula": {
            "agent": Fore.MAGENTA,
            "user": Fore.CYAN,
            "system": Fore.WHITE,
            "command": Fore.LIGHTYELLOW_EX,
            "tool": Fore.LIGHTMAGENTA_EX,
            "shell": Fore.LIGHTCYAN_EX,
            "output": Fore.LIGHTCYAN_EX,
            "error": Fore.RED,
            "success": Fore.GREEN,
            "warning": Fore.YELLOW,
            "dim": Style.DIM,
            "reset": Style.RESET_ALL
        },
        "matrix": {
            "agent": Fore.GREEN,
            "user": Fore.LIGHTGREEN_EX,
            "system": Fore.LIGHTBLACK_EX,
            "command": Fore.YELLOW,
            "tool": Fore.LIGHTGREEN_EX,
            "shell": Fore.CYAN,
            "output": Fore.WHITE,
            "error": Fore.RED,
            "success": Fore.LIGHTGREEN_EX,
            "warning": Fore.YELLOW,
            "dim": Style.DIM,
            "reset": Style.RESET_ALL
        },
        "monokai": {
            "agent": Fore.YELLOW,
            "user": Fore.LIGHTBLUE_EX,
            "system": Fore.WHITE,
            "command": Fore.LIGHTMAGENTA_EX,
            "tool": Fore.MAGENTA,
            "shell": Fore.CYAN,
            "output": Fore.LIGHTGREEN_EX,
            "error": Fore.RED,
            "success": Fore.GREEN,
            "warning": Fore.MAGENTA,
            "dim": Style.DIM,
            "reset": Style.RESET_ALL
        },
        "cyberpunk": {
            "agent": Fore.CYAN,
            "user": Fore.MAGENTA,
            "system": Fore.YELLOW,
            "command": Fore.LIGHTRED_EX,
            "tool": Fore.LIGHTYELLOW_EX,
            "shell": Fore.LIGHTCYAN_EX,
            "output": Fore.LIGHTCYAN_EX,
            "error": Fore.RED,
            "success": Fore.GREEN,
            "warning": Fore.LIGHTRED_EX,
            "dim": Style.DIM,
            "reset": Style.RESET_ALL
        },
        "default": {
            "agent": Fore.BLUE,
            "user": Fore.GREEN,
            "system": Fore.WHITE,
            "command": Fore.YELLOW,
            "tool": Fore.MAGENTA,
            "shell": Fore.CYAN,
            "output": Fore.CYAN,
            "error": Fore.RED,
            "success": Fore.GREEN,
            "warning": Fore.YELLOW,
            "dim": Style.DIM,
            "reset": Style.RESET_ALL
        }
    }
    
    def __init__(self, scheme_name="default"):
        self.scheme = self.SCHEMES.get(scheme_name, self.SCHEMES["default"])
    
    def get(self, key):
        return self.scheme.get(key, Fore.WHITE)


class AgentCLI:
    """Interactive CLI for Core Coder V5."""
    
    def __init__(self, project_dir: str = ".", enable_memory: bool = True, session_id: str = None):
        """Initialize the CLI."""
        self.project_dir = Path(project_dir).resolve()
        self.enable_memory = enable_memory
        self.session_id = session_id or f"session_{AGENT_CONFIG.get('name', 'agent')}"
        
        # Setup colors
        cli_appearance = AGENT_CONFIG.get("cli_appearance", {})
        scheme_name = cli_appearance.get("color_scheme", "default")
        self.colors = Colors(scheme_name)
        self.c_agent = self.colors.get("agent")
        self.c_user = self.colors.get("user")
        self.c_sys = self.colors.get("system")
        self.c_err = self.colors.get("error")
        self.c_reset = self.colors.get("reset")
        
        # Verify API key
        if AGENT_CONFIG.get("provider") == "groq" and not os.getenv('GROQ_API_KEY'):
            print(f"{self.c_err}[ERROR] Error: GROQ_API_KEY not found in environment{self.c_reset}")
            print("   Please create a .env file with your API key:")
            print("   GROQ_API_KEY=your_key_here")
            sys.exit(1)
        
        # Create agent
        display_name = AGENT_CONFIG.get('name', 'Core Coder V5')
        print(f"{self.c_sys}Initializing {display_name}...{self.c_reset}")
        self.agent = create_agent(
            project_root=str(self.project_dir),
            enable_memory=enable_memory
        )
        
        print(f"{self.colors.get('success')}Agent ready!{self.c_reset}\n")
    
    def reinitialize_model(self):
        """Reinitialize the agent with the new model/provider without restarting CLI."""
        try:
            print(f"\n{self.c_sys}Reinitializing agent with new model...{self.c_reset}")
            
            # Reload config from disk (in case it was modified)
            global AGENT_CONFIG
            AGENT_CONFIG = load_config()
            
            # Recreate the agent with updated config
            self.agent = create_agent(
                project_root=str(self.project_dir),
                enable_memory=self.enable_memory
            )
            
            print(f"{self.colors.get('success')}Model switched successfully!{self.c_reset}")
            print(f"{self.c_sys}Provider: {AGENT_CONFIG.get('provider')}{self.c_reset}")
            print(f"{self.c_sys}Model: {AGENT_CONFIG.get('model_name')}{self.c_reset}")
            return True
        except Exception as e:
            print(f"{self.c_err}Failed to reinitialize model: {e}{self.c_reset}")
            return False
    
    def run(self):
        """Run the interactive CLI."""
        # Display banner (local function, not imported)
        print_banner()
        
        # Display agent info
        display_name = AGENT_CONFIG.get('name', 'Core Coder V5')
        print(f"{self.c_sys}{'='*70}")
        print(f"  {display_name} - Interactive Mode")
        print(f"  Provider: {AGENT_CONFIG.get('provider', 'unknown')} | Model: {AGENT_CONFIG.get('model_name', 'unknown')}")
        print(f"  Memory: {'ON' if self.enable_memory else 'OFF'} | RAG: {'ON' if AGENT_CONFIG.get('enable_rag') else 'OFF'}")
        print(f"{'='*70}{self.c_reset}")
        print()
        print(f"{self.c_sys}Commands:")
        print("  - Type your message and press Enter")
        print("  - Type 'exit' or 'quit' to exit")
        print("  - Type 'clear' to clear screen")
        print(f"  - Type 'help' for help")
        print(f"  - Type '//help' for special commands (e.g., //tools, //status){self.c_reset}")
        print()
        print(f"{self.c_sys}{'='*70}{self.c_reset}\n")
        
        while True:
            try:
                # Get user input
                user_input = input(f"\n{self.c_user}You: {self.c_reset}").strip()
                
                if not user_input:
                    continue
                
                # Handle special commands (//cmd format)
                if user_input.startswith('//'):
                    self.handle_special_command(user_input[2:])
                    continue
                
                # Handle commands
                if user_input.lower() in ['exit', 'quit', 'q']:
                    print(f"\n{self.c_sys}Goodbye!{self.c_reset}\n")
                    break
                
                if user_input.lower() == 'clear':
                    os.system('cls' if os.name == 'nt' else 'clear')
                    continue
                
                if user_input.lower() == 'help':
                    self.show_help()
                    continue
                
                # Send to agent and capture tool outputs
                c_tool = self.colors.get("tool")
                c_shell = self.colors.get("shell")
                c_output = self.colors.get("output")
                
                # Define callback to print tool outputs as they happen
                def print_tool_output(tool_name, tool_input, tool_output):
                    print(f"\n{c_tool}╭─ Tool: {tool_name} ─╮{self.c_reset}")
                    if tool_output:
                        # Print tool output with proper formatting
                        lines = str(tool_output).split('\n')
                        for line in lines:
                            print(f"{c_output}│ {line}{self.c_reset}")
                    print(f"{c_tool}╰{'─' * (len(tool_name) + 12)}╯{self.c_reset}")
                
                # Use chat_with_tool_display to capture tool outputs
                try:
                    result = self.agent.chat_with_tool_display(
                        user_input,
                        session_id=self.session_id,
                        tool_callback=print_tool_output
                    )
                    response = result.get('response', '')
                    tool_calls = result.get('tool_calls', [])
                    
                    # If no tool callback was triggered but we have tool calls, print them now
                    if tool_calls and not any(tc.get('output') for tc in tool_calls):
                        for tc in tool_calls:
                            if tc.get('output'):
                                print_tool_output(tc.get('name', 'unknown'), '', tc.get('output', ''))
                    
                except AttributeError:
                    # Fallback to regular chat if chat_with_tool_display not available
                    response = self.agent.chat(
                        user_input,
                        session_id=self.session_id
                    )
                
                # Store in memory for //memory commands
                if self.enable_memory:
                    _simple_memory.add_message(self.session_id, user_input, response)
                
                # Print agent response
                print(f"\n{self.c_agent}Agent: {self.c_reset}")
                self.print_colorized_response(response)
                
            except KeyboardInterrupt:
                print(f"\n\n{self.c_sys}Goodbye!{self.c_reset}\n")
                break
            except Exception as e:
                print(f"\n{self.c_err}Error: {e}{self.c_reset}\n")
    
    def print_colorized_response(self, response: str):
        """Print response with colorized shell commands and output."""
        c_cmd = self.colors.get("command")
        c_out = self.colors.get("output") 
        c_agent = self.c_agent
        c_reset = self.c_reset
        
        in_code_block = False
        backtick = chr(96)  # backtick character
        code_fence = backtick * 3  # code fence
        
        for line in response.split('\n'):
            stripped = line.strip()
            
            # Check for code block start/end
            if stripped.startswith(code_fence):
                in_code_block = not in_code_block
                print(f"{c_out}{line}{c_reset}")
            # Inside code block - everything gets output color
            elif in_code_block:
                # But shell prompts get command color
                if stripped.startswith('$ ') or stripped.startswith('> ') or stripped.startswith('PS '):
                    print(f"{c_cmd}{line}{c_reset}")
                else:
                    print(f"{c_out}{line}{c_reset}")
            # Shell command lines outside code blocks ($ prefix)
            elif stripped.startswith('$ '):
                print(f"{c_cmd}{line}{c_reset}")
            # Regular agent text
            else:
                print(f"{c_agent}{line}{c_reset}")
    
    def handle_special_command(self, cmd: str):
        """Handle special // commands."""
        parts = cmd.split()
        command = parts[0].lower() if parts else ''
        args = parts[1:] if len(parts) > 1 else []
        
        if command == 'tools':
            try:
                from colorama import Fore, Style
                tools = self.agent.list_tools()
                
                print(f"\n{Fore.CYAN}╔════════════════════════════════════════════════════════════╗")
                print(f"║{Style.BRIGHT}                    🛠️  Available Tools{Style.NORMAL}                   ║")
                print(f"╚════════════════════════════════════════════════════════════╝{Style.RESET_ALL}")
                
                if tools:
                    print(f"\n{Fore.WHITE}{Style.BRIGHT}{'#':<4} {'Tool Name':<40}{Style.RESET_ALL}")
                    print(f"{Fore.CYAN}{'─' * 4} {'─' * 40}{Style.RESET_ALL}")
                    
                    for i, tool in enumerate(tools, 1):
                        # Alternate colors for better readability
                        color = Fore.GREEN if i % 2 == 0 else Fore.YELLOW
                        print(f"{color}{i:<4}{Style.RESET_ALL} {Fore.WHITE}{tool}{Style.RESET_ALL}")
                    
                    print(f"\n{Fore.CYAN}Total: {len(tools)} tools loaded{Style.RESET_ALL}")
                else:
                    print(f"\n{self.c_err}  No tools currently loaded{self.c_reset}")
            except Exception as e:
                print(f"\n{self.c_err}  Unable to list tools: {e}{self.c_reset}")
        
        elif command == 'status':
            print(f"\n{self.c_sys}Agent Status:{self.c_reset}")
            print(f"  Name: {AGENT_CONFIG.get('name', 'Agent')}")
            print(f"  Provider: {AGENT_CONFIG.get('provider', 'unknown')}")
            print(f"  Model: {AGENT_CONFIG.get('model_name', 'unknown')}")
            print(f"  Temperature: {AGENT_CONFIG.get('temperature', 0.0)}")
            print(f"  Memory: {'Enabled' if self.enable_memory else 'Disabled'}")
            print(f"  RAG: {'Enabled' if AGENT_CONFIG.get('enable_rag') else 'Disabled'}")
            print(f"  Session: {self.session_id}")
        
        elif command == 'config':
            from colorama import Fore, Style
            
            print(f"\n{Fore.MAGENTA}╔════════════════════════════════════════════════════════════╗")
            print(f"║{Style.BRIGHT}                  ⚙️  Agent Configuration{Style.NORMAL}                  ║")
            print(f"╚════════════════════════════════════════════════════════════╝{Style.RESET_ALL}")
            
            # Core settings
            print(f"\n{Fore.CYAN}{Style.BRIGHT}Core Settings:{Style.RESET_ALL}")
            print(f"  {Fore.WHITE}Name:{Style.RESET_ALL}        {Fore.GREEN}{AGENT_CONFIG.get('name', 'N/A')}{Style.RESET_ALL}")
            print(f"  {Fore.WHITE}Provider:{Style.RESET_ALL}    {Fore.YELLOW}{AGENT_CONFIG.get('provider', 'unknown')}{Style.RESET_ALL}")
            print(f"  {Fore.WHITE}Model:{Style.RESET_ALL}       {Fore.YELLOW}{AGENT_CONFIG.get('model_name', 'unknown')}{Style.RESET_ALL}")
            print(f"  {Fore.WHITE}Temperature:{Style.RESET_ALL} {Fore.CYAN}{AGENT_CONFIG.get('temperature', 0.0)}{Style.RESET_ALL}")
            print(f"  {Fore.WHITE}Max Tokens:{Style.RESET_ALL}  {Fore.CYAN}{AGENT_CONFIG.get('max_tokens', 'N/A')}{Style.RESET_ALL}")
            
            # Features
            print(f"\n{Fore.CYAN}{Style.BRIGHT}Features:{Style.RESET_ALL}")
            mem_status = f"{Fore.GREEN}✓ Enabled" if AGENT_CONFIG.get('enable_memory') else f"{Fore.RED}✗ Disabled"
            rag_status = f"{Fore.GREEN}✓ Enabled" if AGENT_CONFIG.get('enable_rag') else f"{Fore.RED}✗ Disabled"
            shell_status = f"{Fore.GREEN}✓ Enabled" if AGENT_CONFIG.get('enable_shell') else f"{Fore.RED}✗ Disabled"
            print(f"  {Fore.WHITE}Memory:{Style.RESET_ALL}      {mem_status}{Style.RESET_ALL}")
            print(f"  {Fore.WHITE}RAG:{Style.RESET_ALL}         {rag_status}{Style.RESET_ALL}")
            print(f"  {Fore.WHITE}Shell:{Style.RESET_ALL}       {shell_status}{Style.RESET_ALL}")
            
            # Toolboxes
            toolboxes = AGENT_CONFIG.get('toolboxes', [])
            print(f"\n{Fore.CYAN}{Style.BRIGHT}Toolboxes:{Style.RESET_ALL}")
            if toolboxes:
                for tb in toolboxes:
                    print(f"  {Fore.GREEN}• {tb}{Style.RESET_ALL}")
            else:
                print(f"  {Fore.YELLOW}None configured{Style.RESET_ALL}")
            
            # Appearance
            print(f"\n{Fore.CYAN}{Style.BRIGHT}Appearance:{Style.RESET_ALL}")
            print(f"  {Fore.WHITE}Color Scheme:{Style.RESET_ALL}  {Fore.MAGENTA}{AGENT_CONFIG.get('color_scheme', 'default')}{Style.RESET_ALL}")
            print(f"  {Fore.WHITE}Banner Order:{Style.RESET_ALL}  {Fore.MAGENTA}{AGENT_CONFIG.get('banner_order', 'N/A')}{Style.RESET_ALL}")
            print(f"  {Fore.WHITE}Pixel Art:{Style.RESET_ALL}     {Fore.MAGENTA}{'Yes' if AGENT_CONFIG.get('show_pixel_art') else 'No'}{Style.RESET_ALL}")
        
        elif command == 'clear' or command == 'cls':
            os.system('cls' if os.name == 'nt' else 'clear')
        
        elif command == 'help':
            self.show_help()
        
        elif command == 'ollama':
            # List available Ollama models
            if not args or args[0] == 'list':
                try:
                    import requests
                    from colorama import Fore, Style
                    
                    print(f"\n{Fore.CYAN}╔══════════════════════════════════════════════════════════════════════╗")
                    print(f"║{Style.BRIGHT}              🦙 Available Ollama Models{Style.NORMAL}                      ║")
                    print(f"╚══════════════════════════════════════════════════════════════════════╝{Style.RESET_ALL}")
                    
                    response = requests.get('http://localhost:11434/api/tags')
                    if response.status_code == 200:
                        models = response.json().get('models', [])
                        if models:
                            print(f"\n{Fore.WHITE}{Style.BRIGHT}{'Model Name':<35} {'Size':>10}{Style.RESET_ALL}")
                            print(f"{Fore.CYAN}{'─' * 35} {'─' * 10}{Style.RESET_ALL}")
                            
                            # Sort models by name
                            sorted_models = sorted(models, key=lambda x: x.get('name', ''))
                            
                            for model in sorted_models:
                                name = model.get('name', 'unknown')
                                size = model.get('size', 0)
                                size_gb = size / (1024**3) if size else 0
                                
                                # Color code by size
                                if size_gb < 1:
                                    color = Fore.GREEN
                                elif size_gb < 5:
                                    color = Fore.YELLOW
                                else:
                                    color = Fore.MAGENTA
                                
                                print(f"{color}  {name:<33}{Style.RESET_ALL} {Fore.WHITE}{size_gb:>8.2f} GB{Style.RESET_ALL}")
                            
                            print(f"\n{Fore.CYAN}Total: {len(models)} models{Style.RESET_ALL}")
                        else:
                            print(f"\n  {self.c_err}No Ollama models found{self.c_reset}")
                    else:
                        print(f"\n  {self.c_err}Failed to connect to Ollama (status {response.status_code}){self.c_reset}")
                except requests.exceptions.ConnectionError:
                    print(f"\n  {self.c_err}❌ Ollama is not running. Start it with 'ollama serve'{self.c_reset}")
                except Exception as e:
                    print(f"\n  {self.c_err}Error: {e}{self.c_reset}")
            else:
                print(f"\n{self.c_err}Unknown ollama subcommand: {args[0]}{self.c_reset}")
                print(f"{self.c_sys}Usage: //ollama list{self.c_reset}")
        
        elif command == 'groq':
            # List available Groq models
            if not args or args[0] == 'list':
                from colorama import Fore, Style
                
                print(f"\n{Fore.MAGENTA}╔══════════════════════════════════════════════════════════════════════╗")
                print(f"║{Style.BRIGHT}              ⚡ Available Groq Models{Style.NORMAL}                        ║")
                print(f"╚══════════════════════════════════════════════════════════════════════╝{Style.RESET_ALL}")
                
                models = [
                    ("llama-3.3-70b-versatile", "Llama 3.3 70B", "Fastest, Recommended"),
                    ("llama-3.1-70b-versatile", "Llama 3.1 70B", "High quality"),
                    ("llama-3.1-8b-instant", "Llama 3.1 8B", "Ultra fast"),
                    ("mixtral-8x7b-32768", "Mixtral 8x7B", "Long context (32k)"),
                    ("gemma2-9b-it", "Gemma 2 9B", "Instruction tuned"),
                    ("qwen/qwen3-32b", "Qwen 3 32B", "High quality"),
                    ("openai/gpt-oss-120b", "GPT OSS 120B", "Largest model"),
                ]
                
                print(f"\n{Fore.WHITE}{Style.BRIGHT}{'Model ID':<28} {'Name':<18} {'Notes'}{Style.RESET_ALL}")
                print(f"{Fore.MAGENTA}{'─' * 28} {'─' * 18} {'─' * 22}{Style.RESET_ALL}")
                
                for model_id, name, notes in models:
                    print(f"{Fore.CYAN}  {model_id:<26}{Style.RESET_ALL} {Fore.YELLOW}{name:<18}{Style.RESET_ALL} {Fore.WHITE}{notes}{Style.RESET_ALL}")
                
                print(f"\n{Fore.MAGENTA}💡 Tip: Use //model groq <model_id> to switch models{Style.RESET_ALL}")
                print(f"{Fore.WHITE}   Note: Model availability may vary. Check Groq console for latest.{Style.RESET_ALL}")
            else:
                print(f"\n{self.c_err}Unknown groq subcommand: {args[0]}{self.c_reset}")
                print(f"{self.c_sys}Usage: //groq list{self.c_reset}")
        
        elif command == 'model':
            # Switch model - always requires provider
            if len(args) < 2:
                print(f"\n{self.c_err}Usage: //model <provider> <model_name>{self.c_reset}")
                print(f"{self.c_sys}Example: //model ollama qwen3:4b{self.c_reset}")
                print(f"{self.c_sys}Example: //model groq llama-3.3-70b-versatile{self.c_reset}")
                print(f"\n{self.c_sys}Current provider: {AGENT_CONFIG.get('provider', 'unknown')}{self.c_reset}")
                print(f"{self.c_sys}Current model: {AGENT_CONFIG.get('model_name', 'unknown')}{self.c_reset}")
                print(f"{self.c_sys}Use //groq list or //ollama list to see available models{self.c_reset}")
            else:
                new_provider = args[0].lower()
                if new_provider not in ['groq', 'ollama']:
                    print(f"\n{self.c_err}Invalid provider: {args[0]}{self.c_reset}")
                    print(f"{self.c_sys}Available providers: groq, ollama{self.c_reset}")
                else:
                    new_model = ' '.join(args[1:])
                    AGENT_CONFIG['provider'] = new_provider
                    AGENT_CONFIG['model_name'] = new_model
                    save_config()  # Persist the change
                    self.reinitialize_model()  # Hot-swap
        
        elif command == 'rag':
            # RAG commands
            if not args or args[0] == 'status':
                print(f"\n{self.c_sys}RAG (Retrieval Augmented Generation) Status:{self.c_reset}")
                print(f"  Enabled: {AGENT_CONFIG.get('enable_rag', False)}")
                if self.agent.rag_manager:
                    print(f"  Manager: ✓ Initialized")
                    try:
                        collections = self.agent.rag_manager.list_collections()
                        print(f"  Collections: {len(collections)}")
                        for coll in collections:
                            print(f"    - {coll}")
                    except:
                        print(f"  Collections: Unable to retrieve")
                else:
                    print(f"  Manager: ✗ Not initialized")
                    print(f"\n{self.c_sys}RAG requires Qdrant and HuggingFace embeddings to be installed.{self.c_reset}")
            elif args[0] == 'search':
                if len(args) < 2:
                    print(f"\n{self.c_err}Usage: //rag search <query>{self.c_reset}")
                else:
                    query = ' '.join(args[1:])
                    if self.agent.rag_manager:
                        try:
                            # Try to search
                            print(f"\n{self.c_sys}Searching RAG for: {query}{self.c_reset}")
                            # This would need actual implementation based on RAGManager
                            print(f"{self.c_sys}RAG search not yet implemented in CLI{self.c_reset}")
                        except Exception as e:
                            print(f"\n{self.c_err}RAG search error: {e}{self.c_reset}")
                    else:
                        print(f"\n{self.c_err}RAG is not enabled or initialized{self.c_reset}")
            else:
                print(f"\n{self.c_err}Unknown rag subcommand: {args[0]}{self.c_reset}")
                print(f"{self.c_sys}Usage: //rag status | //rag search <query>{self.c_reset}")
        
        elif command == 'memory':
            # Memory commands
            if not args or args[0] == 'status':
                print(f"\n{self.c_sys}Memory Status:{self.c_reset}")
                print(f"  Enabled: {self.enable_memory}")
                if self.agent.simple_memory:
                    history = self.agent.simple_memory.get_history(self.session_id)
                    print(f"  Simple Memory: ✓ Active ({len(history)} messages)")
                if self.agent.memory_manager:
                    print(f"  Advanced Memory: ✓ Active (Qdrant)")
                if not self.agent.simple_memory and not self.agent.memory_manager:
                    print(f"  Memory: ✗ Not available")
            elif args[0] == 'clear':
                if self.agent.simple_memory:
                    self.agent.simple_memory.clear(self.session_id)
                    print(f"\n{self.colors.get('success')}✓ Memory cleared{self.c_reset}")
                else:
                    print(f"\n{self.c_err}No memory to clear{self.c_reset}")
            elif args[0] == 'show':
                if self.agent.simple_memory:
                    history = self.agent.simple_memory.get_history(self.session_id)
                    if history:
                        print(f"\n{self.c_sys}Conversation History ({len(history)} messages):{self.c_reset}")
                        for i, msg in enumerate(history[-5:], 1):  # Show last 5
                            print(f"  {i}. You: {msg['message'][:50]}...")
                            print(f"     Agent: {msg['response'][:50]}...")
                    else:
                        print(f"\n{self.c_sys}No conversation history{self.c_reset}")
                else:
                    print(f"\n{self.c_err}Memory not available{self.c_reset}")
            else:
                print(f"\n{self.c_err}Unknown memory subcommand: {args[0]}{self.c_reset}")
                print(f"{self.c_sys}Usage: //memory status | //memory clear | //memory show{self.c_reset}")
        
        else:
            print(f"\n{self.c_err}Unknown command: //{command}{self.c_reset}")
            print(f"{self.c_sys}Available commands: tools, status, config, clear, help, ollama, groq, model, rag, memory{self.c_reset}")
    
    def show_help(self):
        """Show help information."""
        print(f"\n{self.c_sys}" + "="*70)
        print(f"  {AGENT_CONFIG.get('name', 'Agent')} - Help")
        print("="*70)
        print()
        print("Basic Commands:")
        print("  exit, quit, q  - Exit the CLI")
        print("  clear          - Clear the screen")
        print("  help           - Show this help message")
        print()
        print("Special Commands (// prefix):")
        print("  //tools        - List all available tools")
        print("  //status       - Show agent status and configuration")
        print("  //config       - Show full configuration")
        print("  //ollama list  - List available Ollama models")
        print("  //groq list    - List available Groq models")
        print("  //model <provider> <name> - Switch provider and model")
        print("  //memory status|clear|show - Manage conversation memory")
        print("  //rag status|search <query> - RAG knowledge base")
        print("  //clear        - Clear the screen")
        print("  //help         - Show this help")
        print()
        print("Agent Features:")
        print(f"  - Provider: {AGENT_CONFIG.get('provider', 'unknown')}")
        print(f"  - Model: {AGENT_CONFIG.get('model_name', 'unknown')}")
        print(f"  - Temperature: {AGENT_CONFIG.get('temperature', 0.0)}")
        print(f"  - Memory: {'Enabled' if self.enable_memory else 'Disabled'}")
        history = _simple_memory.get_history(self.session_id)
        if history:
            print(f"    └─ Messages in context: {len(history)}")
        print(f"  - RAG: {'Enabled' if AGENT_CONFIG.get('enable_rag') else 'Disabled'}")
        try:
            print(f"  - Tools: {len(self.agent.tools)} available")
        except:
            print(f"  - Tools: Available")
        print()
        print(f"="*70 + f"{self.c_reset}")


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description=f"{AGENT_CONFIG.get('name', 'Agent')} - CLI Interface",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python cli.py                          # Start interactive mode
  python cli.py --no-memory              # Start without memory
  python cli.py /path/to/project         # Specify project directory
  python cli.py --session my_session     # Custom session ID
        """
    )
    
    parser.add_argument(
        "project_dir",
        nargs="?",
        default=".",
        help="Project directory (default: current directory)"
    )
    
    parser.add_argument(
        "--no-memory",
        action="store_true",
        help="Disable memory and RAG"
    )
    
    parser.add_argument(
        "--session",
        type=str,
        default=None,
        help="Custom session ID"
    )
    
    args = parser.parse_args()
    
    # Validate project directory
    project_path = Path(args.project_dir).resolve()
    if not project_path.exists():
        print(f"❌ Error: Directory does not exist: {args.project_dir}")
        sys.exit(1)
    
    if not project_path.is_dir():
        print(f"❌ Error: Not a directory: {args.project_dir}")
        sys.exit(1)
    
    # Start CLI
    enable_memory = not args.no_memory
    cli = AgentCLI(
        str(project_path),
        enable_memory=enable_memory,
        session_id=args.session
    )
    cli.run()


if __name__ == "__main__":
    main()
